# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b2303ab748ba60c8f42b391657589112841bb29a4ec8c1861f497d4d2926339047fce32fbab077dd4f0d156260534428cb3b20eb6dc681793145ba560eb130

test:
  secret_key_base: 33f0bdd000c101c8edceaad80506c0f5783ff759bceafae6b7ea6a8a77b039dc527e852b55cf987f57e0741f1fe5fdcadbc291861c6fecc0c1cd9b07e6796b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
